name: Continuous Integration

on:
  push:
    branches-ignore:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
  security_audit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Audit
        run: cargo audit
  format_and_clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: FMT
      run: cargo fmt --verbose
    - name: Clippy
      run: cargo clippy --verbose
  build:
    runs-on: ubuntu-latest
    needs: ["security_audit", "format_and_clippy"]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
